import artwork from './artwork'
import banner from './banner'
import debut from './debut'
import general from './general'
import logo from './logo'
import otherComms from './otherComms'
import overlay from './overlay'
import panels from './panels'
import schedule from './schedule'
import screen from './screen'
export const schemaTypes = [general,artwork,overlay,logo,panels,schedule,screen,banner,debut,otherComms]
